all:
  vars:
    app_server_address: "10.1.20.11"

  children:
    servers:
      hosts:
        10.1.1.5:
          ansible_connection: ssh
          app_server_gateway: "10.1.20.1"
          ansible_ssh_private_key_file: "/User/menger/Downloads/f5uberdemo.pem"

    big_ips:
      hosts:
        10.1.1.4:
          bigip_provider:
            server: "{{ inventory_hostname }}"
            user: admin
            password: admin
            validate_certs: false
          bigip_domain: "us-west-2.compute.internal"
          bigip_hostname: "ip-{{ inventory_hostname | replace('.', '-')}}.{{ bigip_domain }}"
          bigip_ntp_server: "\"0.pool.ntp.org\", \"1.pool.ntp.org\""
          bigip_ntp_timezone: "America/Los_Angeles"
          bigip_dns_server: "\"10.1.255.254\""
          bigip_dns_search: "\"{{ bigip_domain }}\""
          bigip_external_self_ip: "10.1.10.241/24"
          bigip_internal_self_ip: "10.1.20.241/24"
          app_virtual_address: "10.1.10.20"

          # BIG-IP license key. Only declare this variable if you desire the licensing task in Declarative Onboarding to run.
          # bigip_license: "AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE"
